import 'package:flutter/material.dart';

import 'style.dart';

// icons
const Map<String, IconData> iconList = {
  // Household
  'home': Icons.home,
  'weekend': Icons.weekend,
  'blender': Icons.blender,
  'construction': Icons.construction,
  'shopping_cart': Icons.shopping_cart,
  'dry_cleaning': Icons.dry_cleaning,
  'checkroom': Icons.checkroom,
  'lightbulb': Icons.lightbulb,
  'electrical_services': Icons.electrical_services,
  'energy_savings_leaf': Icons.energy_savings_leaf,
  'router': Icons.router,
  'device_thermostat': Icons.device_thermostat,
  'water_drop': Icons.water_drop,
  'local_fire_department': Icons.local_fire_department,
  'local_gas_station': Icons.local_gas_station,
  'ev_station': Icons.ev_station,
  'bakery_dining': Icons.bakery_dining,
  'cookie': Icons.cookie,
  'fastfood': Icons.fastfood,
  'toys': Icons.toys_outlined,
  'cake': Icons.cake,
  'gavel': Icons.balance,
  'ramen_dining': Icons.ramen_dining,
  'liquor': Icons.liquor,
  'restaurant': Icons.restaurant,
  'medical_services': Icons.medical_services,
  'vaccines': Icons.vaccines,

  // Activities
  'work': Icons.work,
  'school': Icons.school,
  'calendar_month': Icons.calendar_month,
  'videogame_asset': Icons.videogame_asset,
  'translate': Icons.translate,
  'menu_book': Icons.menu_book,
  'palette': Icons.palette,
  'biotech': Icons.biotech,
  'draw': Icons.draw,
  'celebration': Icons.celebration,
  'card_giftcard': Icons.card_giftcard,
  'shopping_bag': Icons.shopping_bag,
  'format_paint': Icons.format_paint,
  'park': Icons.park,
  'attractions': Icons.attractions,
  'stadium': Icons.stadium,
  'theater_comedy': Icons.theater_comedy,
  'local_movies': Icons.local_movies,
  'confirmation_number': Icons.local_activity,
  'subscriptions': Icons.subscriptions,
  'church': Icons.church,
  'storefront': Icons.storefront,
  'beach_access': Icons.beach_access,
  'fitness_center': Icons.fitness_center,
  'military_tech': Icons.military_tech,
  'emoji_events': Icons.emoji_events,
  'sports_motorsports': Icons.sports_motorsports,

  // Travel
  'rocket_launch': Icons.rocket_launch,
  'flight': Icons.flight,
  'airplane_ticket': Icons.airplane_ticket,
  'local_taxi': Icons.local_taxi,
  'directions_boat': Icons.directions_boat,
  'sailing': Icons.sailing,
  'anchor': Icons.anchor,
  'agriculture': Icons.agriculture,
  'commute': Icons.commute,
  'directions_bus': Icons.directions_bus,
  'subway': Icons.subway,
  'tram': Icons.tram,
  'electric_scooter': Icons.electric_scooter,
  'directions_car': Icons.directions_car,
  'directions_car_rounded': Icons.directions_car_rounded,
  'electric_car': Icons.electric_car,
  'directions_bike': Icons.directions_bike,
  'electric_bike': Icons.electric_bike,
  'two_wheeler': Icons.two_wheeler,
  'moped': Icons.moped,
  'electric_moped': Icons.electric_moped,
  'public': Icons.public,
  'place': Icons.place,
  'hotel': Icons.hotel,
  'luggage': Icons.luggage,
  'airline_seat_recline_normal': Icons.airline_seat_recline_normal,

  // Tech
  'monitor': Icons.monitor,
  'laptop': Icons.laptop,
  'desktop_mac': Icons.desktop_mac,
  'devices': Icons.devices,
  'phone': Icons.phone,
  'sim_card': Icons.sim_card,
  'camera_alt': Icons.camera_alt,
  'image': Icons.image,
  'language': Icons.language,
  'album': Icons.album,
  'video_library': Icons.video_library,
  'music_note': Icons.music_note,
  'cloud': Icons.cloud,
  'call': Icons.call,
  'headphones': Icons.headphones,
  'shield': Icons.shield,
  'email': Icons.email,
  'drafts': Icons.drafts,

  // People
  'wc': Icons.wc,
  'pregnant_woman': Icons.pregnant_woman,
  'diversity_3': Icons.diversity_3,
  'family_restroom': Icons.family_restroom,
  'accessible': Icons.accessible,
  'elderly': Icons.elderly,
  'elderly_woman': Icons.elderly_woman,
  'self_improvement': Icons.self_improvement,
  'sports_kabaddi': Icons.sports_kabaddi,
  'downhill_skiing': Icons.downhill_skiing,
  'directions_run': Icons.directions_run,
  'hiking': Icons.hiking,
  'child_care': Icons.child_care,

  // Others
  'real_estate_agent': Icons.real_estate_agent,
  'show_chart': Icons.show_chart,
  'diamond': Icons.diamond,
  'local_parking': Icons.local_parking,
  'circle': Icons.circle,
  'key': Icons.key,
  'bolt': Icons.bolt,
  'local_florist': Icons.local_florist,
  'ac_unit': Icons.ac_unit,
  'wb_sunny': Icons.wb_sunny,
  'nights_stay': Icons.nights_stay,
  'recycling': Icons.recycling,
  'favorite': Icons.favorite,
  'star': Icons.star,
  'priority_high': Icons.priority_high,
  'volunteer_activism': Icons.volunteer_activism,
  'psychology': Icons.psychology,
  'push_pin': Icons.push_pin,
  'help': Icons.help,
  'flag': Icons.flag,
  'percent': Icons.percent,
  'block': Icons.block,
  'link': Icons.link,
  'sos': Icons.sos,
};

const Map<String, IconData> accountIconList = {
  'payments': Icons.payments,
  'credit_card': Icons.credit_card,
  'savings': Icons.savings,
  'account_balance': Icons.account_balance,
};

// colors
const categoryColorList = [
  category1,
  category2,
  category3,
  category4,
  category5,
  category6,
  category7,
  category8,
  category9,
  category10,
  category11,
  category12,
  category13,
  category14,
  category15,
  category16,
  category17,
  category18,
  category19,
  category20,
  category21,
  category22,
  category23,
  category24,
  category25,
  category26,
  category27,
  category28,
  category29,
  category30,
  category31,
  category32,
  category33,
  category34,
  category35,
  category36,
  category37,
  category38,
  category39,
  category40,
  category41,
  category42,
  category43,
  category44,
  category45,
  category46,
  category47,
  category48,
  category49,
  category50,
  category51,
];

const darkCategoryColorList = [
  darkCategory1,
  darkCategory2,
  darkCategory3,
  darkCategory4,
  darkCategory5,
  darkCategory6,
  darkCategory7,
  darkCategory8,
  darkCategory9,
  darkCategory10,
  darkCategory11,
  darkCategory12,
  darkCategory13,
  darkCategory14,
  darkCategory15,
  darkCategory16,
  darkCategory17,
  darkCategory18,
  darkCategory19,
  darkCategory20,
  darkCategory21,
  darkCategory22,
  darkCategory23,
  darkCategory24,
  darkCategory25,
  darkCategory26,
  darkCategory27,
  darkCategory28,
  darkCategory29,
  darkCategory30,
  darkCategory31,
  darkCategory32,
  darkCategory33,
  darkCategory34,
  darkCategory35,
  darkCategory36,
  darkCategory37,
  darkCategory38,
  darkCategory39,
  darkCategory40,
  darkCategory41,
  darkCategory42,
  darkCategory43,
  darkCategory44,
  darkCategory45,
  darkCategory46,
  darkCategory47,
  darkCategory48,
  darkCategory49,
  darkCategory50,
  darkCategory51,
];

const accountColorList = [
  account1,
  account2,
  account3,
  account4,
  account5,
];

const darkAccountColorList = [
  darkAccount1,
  darkAccount2,
  darkAccount3,
  darkAccount4,
  darkAccount5,
];

List<Color> categoryColorListTheme = categoryColorList;
List<Color> accountColorListTheme = accountColorList;

void updateColorsBasedOnTheme(bool isDarkModeEnabled) {
  if (isDarkModeEnabled) {
    categoryColorListTheme = darkCategoryColorList;
    accountColorListTheme = darkAccountColorList;
  } else {
    categoryColorListTheme = categoryColorList;
    accountColorListTheme = accountColorList;
  }
}
