name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: ["RIP-Comm/3"]
assignees:
  - theperu
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What OS are you on?
      options:
        - Android
        - Apple
      default: 0
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: What version?
      description: Also tell us, what did you expect to happen?
      placeholder: e.g. Android 14 or iOS 18.3.2
    validations:
      required: true  
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.1.0
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log or screenshots
      description: Please copy and paste any relevant log output if appliable (e.g. logcat) or copy-paste your screenshots here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you confirm that you have previously used the search function to look for the same issue among both open and closed issues. 
      options:
        - label: I agree
          required: true
