// Mocks generated by Mockito 5.4.4 from annotations
// in sossoldi/test/gdrive/google_drive_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:_discoveryapis_commons/_discoveryapis_commons.dart' as _i4;
import 'package:googleapis/drive/v3.dart' as _i2;
import 'package:googleapis/shared.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAboutResource_0 extends _i1.SmartFake implements _i2.AboutResource {
  _FakeAboutResource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChangesResource_1 extends _i1.SmartFake
    implements _i2.ChangesResource {
  _FakeChangesResource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelsResource_2 extends _i1.SmartFake
    implements _i2.ChannelsResource {
  _FakeChannelsResource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentsResource_3 extends _i1.SmartFake
    implements _i2.CommentsResource {
  _FakeCommentsResource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDrivesResource_4 extends _i1.SmartFake
    implements _i2.DrivesResource {
  _FakeDrivesResource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFilesResource_5 extends _i1.SmartFake implements _i2.FilesResource {
  _FakeFilesResource_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePermissionsResource_6 extends _i1.SmartFake
    implements _i2.PermissionsResource {
  _FakePermissionsResource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRepliesResource_7 extends _i1.SmartFake
    implements _i2.RepliesResource {
  _FakeRepliesResource_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRevisionsResource_8 extends _i1.SmartFake
    implements _i2.RevisionsResource {
  _FakeRevisionsResource_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeamdrivesResource_9 extends _i1.SmartFake
    implements _i2.TeamdrivesResource {
  _FakeTeamdrivesResource_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_10 extends _i1.SmartFake implements _i2.File {
  _FakeFile_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedIds_11 extends _i1.SmartFake implements _i2.GeneratedIds {
  _FakeGeneratedIds_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_12 extends _i1.SmartFake implements Object {
  _FakeObject_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileList_13 extends _i1.SmartFake implements _i2.FileList {
  _FakeFileList_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLabelList_14 extends _i1.SmartFake implements _i2.LabelList {
  _FakeLabelList_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModifyLabelsResponse_15 extends _i1.SmartFake
    implements _i2.ModifyLabelsResponse {
  _FakeModifyLabelsResponse_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DriveApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveApi extends _i1.Mock implements _i2.DriveApi {
  MockDriveApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AboutResource get about => (super.noSuchMethod(
        Invocation.getter(#about),
        returnValue: _FakeAboutResource_0(
          this,
          Invocation.getter(#about),
        ),
      ) as _i2.AboutResource);

  @override
  _i2.ChangesResource get changes => (super.noSuchMethod(
        Invocation.getter(#changes),
        returnValue: _FakeChangesResource_1(
          this,
          Invocation.getter(#changes),
        ),
      ) as _i2.ChangesResource);

  @override
  _i2.ChannelsResource get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: _FakeChannelsResource_2(
          this,
          Invocation.getter(#channels),
        ),
      ) as _i2.ChannelsResource);

  @override
  _i2.CommentsResource get comments => (super.noSuchMethod(
        Invocation.getter(#comments),
        returnValue: _FakeCommentsResource_3(
          this,
          Invocation.getter(#comments),
        ),
      ) as _i2.CommentsResource);

  @override
  _i2.DrivesResource get drives => (super.noSuchMethod(
        Invocation.getter(#drives),
        returnValue: _FakeDrivesResource_4(
          this,
          Invocation.getter(#drives),
        ),
      ) as _i2.DrivesResource);

  @override
  _i2.FilesResource get files => (super.noSuchMethod(
        Invocation.getter(#files),
        returnValue: _FakeFilesResource_5(
          this,
          Invocation.getter(#files),
        ),
      ) as _i2.FilesResource);

  @override
  _i2.PermissionsResource get permissions => (super.noSuchMethod(
        Invocation.getter(#permissions),
        returnValue: _FakePermissionsResource_6(
          this,
          Invocation.getter(#permissions),
        ),
      ) as _i2.PermissionsResource);

  @override
  _i2.RepliesResource get replies => (super.noSuchMethod(
        Invocation.getter(#replies),
        returnValue: _FakeRepliesResource_7(
          this,
          Invocation.getter(#replies),
        ),
      ) as _i2.RepliesResource);

  @override
  _i2.RevisionsResource get revisions => (super.noSuchMethod(
        Invocation.getter(#revisions),
        returnValue: _FakeRevisionsResource_8(
          this,
          Invocation.getter(#revisions),
        ),
      ) as _i2.RevisionsResource);

  @override
  _i2.TeamdrivesResource get teamdrives => (super.noSuchMethod(
        Invocation.getter(#teamdrives),
        returnValue: _FakeTeamdrivesResource_9(
          this,
          Invocation.getter(#teamdrives),
        ),
      ) as _i2.TeamdrivesResource);
}

/// A class which mocks [FilesResource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilesResource extends _i1.Mock implements _i2.FilesResource {
  MockFilesResource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.File> copy(
    _i2.File? request,
    String? fileId, {
    bool? enforceSingleParent,
    bool? ignoreDefaultVisibility,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #copy,
          [
            request,
            fileId,
          ],
          {
            #enforceSingleParent: enforceSingleParent,
            #ignoreDefaultVisibility: ignoreDefaultVisibility,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
          },
        ),
        returnValue: _i3.Future<_i2.File>.value(_FakeFile_10(
          this,
          Invocation.method(
            #copy,
            [
              request,
              fileId,
            ],
            {
              #enforceSingleParent: enforceSingleParent,
              #ignoreDefaultVisibility: ignoreDefaultVisibility,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i3.Future<_i2.File>);

  @override
  _i3.Future<_i2.File> create(
    _i2.File? request, {
    bool? enforceSingleParent,
    bool? ignoreDefaultVisibility,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    bool? useContentAsIndexableText,
    String? $fields,
    _i4.UploadOptions? uploadOptions = _i4.UploadOptions.defaultOptions,
    _i4.Media? uploadMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [request],
          {
            #enforceSingleParent: enforceSingleParent,
            #ignoreDefaultVisibility: ignoreDefaultVisibility,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #useContentAsIndexableText: useContentAsIndexableText,
            #$fields: $fields,
            #uploadOptions: uploadOptions,
            #uploadMedia: uploadMedia,
          },
        ),
        returnValue: _i3.Future<_i2.File>.value(_FakeFile_10(
          this,
          Invocation.method(
            #create,
            [request],
            {
              #enforceSingleParent: enforceSingleParent,
              #ignoreDefaultVisibility: ignoreDefaultVisibility,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #useContentAsIndexableText: useContentAsIndexableText,
              #$fields: $fields,
              #uploadOptions: uploadOptions,
              #uploadMedia: uploadMedia,
            },
          ),
        )),
      ) as _i3.Future<_i2.File>);

  @override
  _i3.Future<void> delete(
    String? fileId, {
    bool? enforceSingleParent,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [fileId],
          {
            #enforceSingleParent: enforceSingleParent,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> emptyTrash({
    bool? enforceSingleParent,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #emptyTrash,
          [],
          {
            #enforceSingleParent: enforceSingleParent,
            #$fields: $fields,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.Media?> export(
    String? fileId,
    String? mimeType, {
    String? $fields,
    _i4.DownloadOptions? downloadOptions = _i4.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #export,
          [
            fileId,
            mimeType,
          ],
          {
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i3.Future<_i4.Media?>.value(),
      ) as _i3.Future<_i4.Media?>);

  @override
  _i3.Future<_i2.GeneratedIds> generateIds({
    int? count,
    String? space,
    String? type,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIds,
          [],
          {
            #count: count,
            #space: space,
            #type: type,
            #$fields: $fields,
          },
        ),
        returnValue: _i3.Future<_i2.GeneratedIds>.value(_FakeGeneratedIds_11(
          this,
          Invocation.method(
            #generateIds,
            [],
            {
              #count: count,
              #space: space,
              #type: type,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i3.Future<_i2.GeneratedIds>);

  @override
  _i3.Future<Object> get(
    String? fileId, {
    bool? acknowledgeAbuse,
    String? includeLabels,
    String? includePermissionsForView,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
    _i4.DownloadOptions? downloadOptions = _i4.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [fileId],
          {
            #acknowledgeAbuse: acknowledgeAbuse,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i3.Future<Object>.value(_FakeObject_12(
          this,
          Invocation.method(
            #get,
            [fileId],
            {
              #acknowledgeAbuse: acknowledgeAbuse,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
              #downloadOptions: downloadOptions,
            },
          ),
        )),
      ) as _i3.Future<Object>);

  @override
  _i3.Future<_i2.FileList> list({
    String? corpora,
    String? corpus,
    String? driveId,
    bool? includeItemsFromAllDrives,
    String? includeLabels,
    String? includePermissionsForView,
    bool? includeTeamDriveItems,
    String? orderBy,
    int? pageSize,
    String? pageToken,
    String? q,
    String? spaces,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? teamDriveId,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #corpora: corpora,
            #corpus: corpus,
            #driveId: driveId,
            #includeItemsFromAllDrives: includeItemsFromAllDrives,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #includeTeamDriveItems: includeTeamDriveItems,
            #orderBy: orderBy,
            #pageSize: pageSize,
            #pageToken: pageToken,
            #q: q,
            #spaces: spaces,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #teamDriveId: teamDriveId,
            #$fields: $fields,
          },
        ),
        returnValue: _i3.Future<_i2.FileList>.value(_FakeFileList_13(
          this,
          Invocation.method(
            #list,
            [],
            {
              #corpora: corpora,
              #corpus: corpus,
              #driveId: driveId,
              #includeItemsFromAllDrives: includeItemsFromAllDrives,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #includeTeamDriveItems: includeTeamDriveItems,
              #orderBy: orderBy,
              #pageSize: pageSize,
              #pageToken: pageToken,
              #q: q,
              #spaces: spaces,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #teamDriveId: teamDriveId,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i3.Future<_i2.FileList>);

  @override
  _i3.Future<_i2.LabelList> listLabels(
    String? fileId, {
    int? maxResults,
    String? pageToken,
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listLabels,
          [fileId],
          {
            #maxResults: maxResults,
            #pageToken: pageToken,
            #$fields: $fields,
          },
        ),
        returnValue: _i3.Future<_i2.LabelList>.value(_FakeLabelList_14(
          this,
          Invocation.method(
            #listLabels,
            [fileId],
            {
              #maxResults: maxResults,
              #pageToken: pageToken,
              #$fields: $fields,
            },
          ),
        )),
      ) as _i3.Future<_i2.LabelList>);

  @override
  _i3.Future<_i2.ModifyLabelsResponse> modifyLabels(
    _i2.ModifyLabelsRequest? request,
    String? fileId, {
    String? $fields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #modifyLabels,
          [
            request,
            fileId,
          ],
          {#$fields: $fields},
        ),
        returnValue: _i3.Future<_i2.ModifyLabelsResponse>.value(
            _FakeModifyLabelsResponse_15(
          this,
          Invocation.method(
            #modifyLabels,
            [
              request,
              fileId,
            ],
            {#$fields: $fields},
          ),
        )),
      ) as _i3.Future<_i2.ModifyLabelsResponse>);

  @override
  _i3.Future<_i2.File> update(
    _i2.File? request,
    String? fileId, {
    String? addParents,
    bool? enforceSingleParent,
    String? includeLabels,
    String? includePermissionsForView,
    bool? keepRevisionForever,
    String? ocrLanguage,
    String? removeParents,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    bool? useContentAsIndexableText,
    String? $fields,
    _i4.UploadOptions? uploadOptions = _i4.UploadOptions.defaultOptions,
    _i4.Media? uploadMedia,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            request,
            fileId,
          ],
          {
            #addParents: addParents,
            #enforceSingleParent: enforceSingleParent,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #keepRevisionForever: keepRevisionForever,
            #ocrLanguage: ocrLanguage,
            #removeParents: removeParents,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #useContentAsIndexableText: useContentAsIndexableText,
            #$fields: $fields,
            #uploadOptions: uploadOptions,
            #uploadMedia: uploadMedia,
          },
        ),
        returnValue: _i3.Future<_i2.File>.value(_FakeFile_10(
          this,
          Invocation.method(
            #update,
            [
              request,
              fileId,
            ],
            {
              #addParents: addParents,
              #enforceSingleParent: enforceSingleParent,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #keepRevisionForever: keepRevisionForever,
              #ocrLanguage: ocrLanguage,
              #removeParents: removeParents,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #useContentAsIndexableText: useContentAsIndexableText,
              #$fields: $fields,
              #uploadOptions: uploadOptions,
              #uploadMedia: uploadMedia,
            },
          ),
        )),
      ) as _i3.Future<_i2.File>);

  @override
  _i3.Future<Object> watch(
    _i5.$Channel? request,
    String? fileId, {
    bool? acknowledgeAbuse,
    String? includeLabels,
    String? includePermissionsForView,
    bool? supportsAllDrives,
    bool? supportsTeamDrives,
    String? $fields,
    _i4.DownloadOptions? downloadOptions = _i4.DownloadOptions.metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watch,
          [
            request,
            fileId,
          ],
          {
            #acknowledgeAbuse: acknowledgeAbuse,
            #includeLabels: includeLabels,
            #includePermissionsForView: includePermissionsForView,
            #supportsAllDrives: supportsAllDrives,
            #supportsTeamDrives: supportsTeamDrives,
            #$fields: $fields,
            #downloadOptions: downloadOptions,
          },
        ),
        returnValue: _i3.Future<Object>.value(_FakeObject_12(
          this,
          Invocation.method(
            #watch,
            [
              request,
              fileId,
            ],
            {
              #acknowledgeAbuse: acknowledgeAbuse,
              #includeLabels: includeLabels,
              #includePermissionsForView: includePermissionsForView,
              #supportsAllDrives: supportsAllDrives,
              #supportsTeamDrives: supportsTeamDrives,
              #$fields: $fields,
              #downloadOptions: downloadOptions,
            },
          ),
        )),
      ) as _i3.Future<Object>);
}
