// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appName => 'Sossoldi';

  @override
  String get dashboard => 'Dashboard';

  @override
  String get transactions => 'Transactions';

  @override
  String get planning => 'Planning';

  @override
  String get graphs => 'Graphs';

  @override
  String get list => 'List';

  @override
  String get categories => 'Categories';

  @override
  String get expenses => 'Expenses';

  @override
  String get incomes => 'Incomes';

  @override
  String get expense => 'Expense';

  @override
  String get income => 'Income';

  @override
  String get transfer => 'Transfer';

  @override
  String get accounts => 'Accounts';

  @override
  String get details => 'Details';

  @override
  String get account => 'Account';

  @override
  String get category => 'Category';

  @override
  String get date => 'Date';

  @override
  String get investments => 'Investments';

  @override
  String get settings => 'Settings';

  @override
  String get notifications => 'Notifications';

  @override
  String get settingsDisclaimer => 'Open source, built by the community';

  @override
  String get addTransaction => 'Add transaction';

  @override
  String get totalBalance => 'Total balance';

  @override
  String get netWorth => 'Net worth';

  @override
  String get save => 'Save';

  @override
  String get cancel => 'Cancel';

  @override
  String get success => 'Success';

  @override
  String get ok => 'Ok';

  @override
  String get editingTransaction => 'Editing transaction';

  @override
  String get newTransaction => 'New transaction';

  @override
  String get updateTransaction => 'Update transaction';

  @override
  String get recurringPayments => 'Recurring payments';

  @override
  String get interval => 'Interval';

  @override
  String get endRepetition => 'End repetition';

  @override
  String get never => 'Never';

  @override
  String get onADate => 'On a date';

  @override
  String get switchDisabled => 'Switch is disabled';

  @override
  String saveCsvFileFailed(Object e) {
    return 'Cannot save the file here, please create or select a folder in Downloads or Documents. Error: $e';
  }

  @override
  String errorPickingFile(Object error) {
    return 'Error picking file. Please ensure you have sufficient permissions. Error: $error';
  }

  @override
  String get storagePermissionRequired =>
      'Storage permission is required to access your files.';

  @override
  String get importingData => 'Importing data...';

  @override
  String get exportingData => 'Exporting data...';

  @override
  String fileSavedTo(Object path) {
    return 'File saved to: $path';
  }

  @override
  String get dataImportedSuccessfully => 'Data imported successfully';

  @override
  String get description => 'Description';

  @override
  String get addDescription => 'Add description';

  @override
  String get recurringTransactionWarning =>
      'This is a transaction generated by a recurring one: any change will affect this unique transaction.\nTo change all future transactions, or recurrence options, TAP HERE.';

  @override
  String get duplicateTransactionTitle => 'Duplicate transaction';

  @override
  String get duplicateTransactionContent =>
      'This transaction is already in the list. Do you want to duplicate it? You can then edit the new transaction.';

  @override
  String get duplicate => 'Duplicate';

  @override
  String get moreFrequent => 'More frequent';

  @override
  String get allCategories => 'All categories';

  @override
  String get allAccounts => 'All accounts';

  @override
  String errorOccurred(Object err) {
    return 'Error: $err';
  }

  @override
  String get selectAccount => 'Select Account';

  @override
  String get to => 'To:';

  @override
  String get from => 'From:';

  @override
  String get recurringTransactionAdded => 'Recurring transaction added';

  @override
  String get recurringTransactions => 'Recurring transactions';

  @override
  String get addTransactionReminder => 'Add transaction reminder';

  @override
  String get privacyPolicyTitle => 'Privacy Policy';

  @override
  String get privacyCollectTitle => 'What Information Do We Collect?';

  @override
  String get privacyChangesTitle => 'Changes to This Privacy Policy';

  @override
  String get contactUsTitle => 'Contact us';

  @override
  String get privacyIntro =>
      'Sossoldi is built as an open source app. This service is provided by us at no cost and it is intended for use as is.\nWe are not interested in collecting any personal information. We believe such information is yours and yours alone. We do not store or transmit your personal details, nor do we include any advertising or analytics software that talks to third parties.\n';

  @override
  String get privacyCollectBody =>
      'Sossoldi does not collect any personal information or connect to the internet. Any information that you add in the app exists solely on your device and nowhere else.\n';

  @override
  String get privacyChangesBody =>
      'We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes.\nThis policy is effective as of 2024-01-01\n';

  @override
  String get contactUsBody =>
      'If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at \n';

  @override
  String get collaboratorsTitle => 'Collaborators';

  @override
  String get meetTheTeam => 'Meet the team';

  @override
  String get teamDescription =>
      'Sossoldi is built and maintained by a passionate open source community. Every feature, fix and idea comes from people like you.';

  @override
  String get wantToContribute => 'Want to contribute?';

  @override
  String get contributeDescription =>
      'Open an issue, submit a PR or just say hi on GitHub';

  @override
  String get appInfo => 'App Info';

  @override
  String get appVersion => 'App Version:';

  @override
  String get collaborators => 'Collaborators';

  @override
  String get collaboratorsDescription => 'See the team behind this app';

  @override
  String get privacyPolicy => 'Privacy Policy';

  @override
  String get privacyPolicyDescription => 'Read more';

  @override
  String get generalSettings => 'General Settings';

  @override
  String get appearance => 'Appearance';

  @override
  String get currency => 'Currency';

  @override
  String get requireAuthentication => 'Require authentication';

  @override
  String get searchForATransaction => 'Search for a transaction';

  @override
  String get selectACurrency => 'Select a currency';

  @override
  String get search => 'Search';

  @override
  String get searchIn => 'Search in';

  @override
  String get lastTransactions => 'Your last transactions';

  @override
  String get startReconciliation => 'Start reconciliation';

  @override
  String get newBalance => 'New balance';

  @override
  String get balanceDiscrepancy => 'Balance Discrepancy?';

  @override
  String get balanceAdjustmentHint =>
      'Your recorded balance might differ from your bank\'s statement. Tap below to manually adjust your balance and keep your records accurate.';

  @override
  String get newAccount => 'New account';

  @override
  String get editAccount => 'Edit account';

  @override
  String get createAccount => 'Create account';

  @override
  String get accountName => 'Account name';

  @override
  String get name => 'Name';

  @override
  String get iconAndColor => 'Icon and color';

  @override
  String get chooseColor => 'Choose color';

  @override
  String get chooseIcon => 'Choose icon';

  @override
  String get done => 'Fatto';

  @override
  String get add => 'Add';

  @override
  String get setAsMainAccount => 'Set as main account';

  @override
  String get countsForNetWorth => 'Counts for the net worth';

  @override
  String get deleteAccount => 'Delete account';

  @override
  String get initialBalance => 'Initial balance';

  @override
  String get currentBalance => 'Current balance';

  @override
  String get showLess => 'Show less';

  @override
  String get showMore => 'Show more';

  @override
  String get addSubcategory => 'Add subcategory';

  @override
  String get newCategory => 'New category';

  @override
  String get editCategory => 'Edit category';

  @override
  String get createCategory => 'Create category';

  @override
  String get updateCategory => 'Update category';

  @override
  String get categoryName => 'Category name';

  @override
  String get type => 'Type';

  @override
  String get deleteCategory => 'Delete category';

  @override
  String get newSubcategory => 'New subcategory';

  @override
  String get editSubcategory => 'Edit subcategory';

  @override
  String get createSubcategory => 'Create subcategory';

  @override
  String get updateSubcategory => 'Update subcategory';

  @override
  String get subcategoryName => 'Subcategory name';

  @override
  String get deleteSubcategory => 'Delete subcategory';

  @override
  String get subcategory => 'Subcategory';

  @override
  String get categoryFirstThenBudget => 'Add a category first to set a budget';

  @override
  String inTheNextDays(Object next) {
    return 'In  $next days';
  }

  @override
  String get monthlyBudget => 'Monthly budget';

  @override
  String get manage => 'Manage';

  @override
  String get swipeLeftToDelete => 'Swipe left to delete';

  @override
  String get yourMonthlyBudgetWillBe => 'Your monthly budget will be:';

  @override
  String get saveBudget => 'Save budget';

  @override
  String get selectCategoriesToCreateBudget =>
      'Select the categories to create your budget';

  @override
  String get amount => 'Amount';

  @override
  String get addCategoryBudget => 'Add category budget';

  @override
  String get allCategoriesAdded =>
      'You have already added all available categories.';

  @override
  String get delete => 'Delete';

  @override
  String get allRecurringPaymentsHere =>
      'All recurring payments will be displayed here';

  @override
  String get addRecurringPayment => 'Add recurring payment';

  @override
  String get seeOlderPayments => 'See older payments';

  @override
  String untilDate(Object date) {
    return 'Until $date';
  }

  @override
  String get olderPayments => 'Older payments';

  @override
  String get categoryNotFound => 'Category not found';

  @override
  String get back => 'Back';

  @override
  String onTheDay(Object day) {
    return '- On the $day day';
  }

  @override
  String get noMonthlyPaymentHistory => 'No monthly payment history';

  @override
  String get noRecurrentPaymentHistory => 'No recurrent payment history';

  @override
  String errorLoadingPayments(Object error) {
    return 'Error loading payments: $error';
  }

  @override
  String get editRecurringTransaction => 'Edit recurring transaction';

  @override
  String get detailsExplanation =>
      'Details (any change will affect only future transactions)';

  @override
  String get dateStart => 'Date start';

  @override
  String get planned => 'Planned';

  @override
  String get composition => 'Composition';

  @override
  String get progress => 'Progress';

  @override
  String get noBudgetSet => 'There are no budgets set';

  @override
  String get budgetHelpText =>
      'A monthly budget can help you keep track of your expenses and stay within the limits';

  @override
  String get createBudget => 'Create budget';

  @override
  String get setUpTheApp => 'Set up the app';

  @override
  String get setupDescription =>
      'In a few steps you\'ll be ready to start keeping\ntrack of your personal finances (almost) like\nMr. Rip.';

  @override
  String get startTheSetup => 'Start the setup';

  @override
  String budgetAmount(Object amount) {
    return 'Budget $amount€';
  }

  @override
  String get addBudget => 'Add budget';

  @override
  String addBudgetForCategory(Object cat) {
    return 'Add budget for category $cat';
  }

  @override
  String get addCategory => 'Add category';

  @override
  String get confirm => 'Confirm';

  @override
  String get step1Of2 => 'Step 1 of 2';

  @override
  String get setupMonthlyBudgets => 'Set up your monthly\nbudgets';

  @override
  String get chooseCategoriesForBudget =>
      'Choose which categories you want to set a budget for';

  @override
  String get monthlyBudgetTotal => 'Monthly budget total:';

  @override
  String get nextStep => 'Next step';

  @override
  String get continueWithoutBudget => 'Continue without budget';

  @override
  String get step2Of2 => 'Step 2 OF 2';

  @override
  String get setLiquidityInMainAccount =>
      'Set the liquidity in your main account';

  @override
  String get addMoreAccounts =>
      'You\'ll be able to add more accounts within the app.';

  @override
  String get liquidityDescription =>
      'It will be used as a baseline to which you can add income, expenses and calculate your wealth.\nYou\'ll be able to add more accounts within the app.';

  @override
  String get mainAccount => 'Main account';

  @override
  String get setAmount => 'Set amount';

  @override
  String get editIconAndColor => 'Edit icon and color';

  @override
  String get skipStepOrStartFromZero =>
      'Or you can skip this step and start from 0';

  @override
  String get startTrackingExpenses => 'Start tracking your expenses';

  @override
  String get startFromZero => 'Start from 0';

  @override
  String get importExport => 'Import/Export';

  @override
  String get importData => 'Import data';

  @override
  String get importDataDescription =>
      'Import a CSV file to update your database';

  @override
  String get importMoneyManager => 'Import from Money Manager';

  @override
  String get importMoneyManagerDescription =>
      'Import CSV from Money Manager to update your database. The file must be saved as CSV from XLS.';

  @override
  String get exportData => 'Export data';

  @override
  String get exportDataDescription => 'Save your data as a CSV file';

  @override
  String get warningOverwrite => 'Warning: Data Overwrite';

  @override
  String get warningOverwriteContent =>
      'Importing this file will permanently replace your existing data. This action cannot be undone. Ensure you have a backup before proceeding.';

  @override
  String get proceedImport => 'Proceed with Import';

  @override
  String get importSuccess => 'Data imported successfully';

  @override
  String exportFailed(Object err) {
    return 'Export failed: $err';
  }

  @override
  String errorExporting(Object tableName) {
    return 'Failed to export table: $tableName';
  }

  @override
  String get errorCsvNotFound => 'CSV file not found.';

  @override
  String get errorCsvEmpty => 'The CSV file is empty.';

  @override
  String errorCsvExpectedColumn(Object column) {
    return 'Missing expected column: $column';
  }

  @override
  String errorCsvUnexpectedValue(Object value) {
    return 'Found an unexpected value: $value';
  }

  @override
  String errorCsvImportGeneral(Object error) {
    return 'A general error occurred during CSV import. With error: $error';
  }

  @override
  String errorCsvTransactionImport(Object date) {
    return 'Failed to import transaction on date: $date';
  }

  @override
  String errorCleanDatabase(Object error) {
    return 'Failed to clean the database. Reason: $error';
  }

  @override
  String errorResetDatabase(Object error) {
    return 'Failed to reset the database. Reason: $error';
  }

  @override
  String transactionCount(Object count) {
    return '$count transactions';
  }

  @override
  String get uncategorized => 'Uncategorized';

  @override
  String get noIncomesForSelectedMonth => 'No incomes for the selected month';

  @override
  String get noExpensesForSelectedMonth => 'No expenses for the selected month';

  @override
  String get total => 'Total';

  @override
  String get noTransactionsAdded => 'There are no transactions added yet';

  @override
  String get addTransactionCallToAction =>
      'Add a transaction to make this section more appealing';

  @override
  String get graphsEmptyState =>
      'After you add some transactions, some outstanding graphs will appear here... almost by magic!';

  @override
  String get availableLiquidity => 'Available liquidity';

  @override
  String get vsLastMonth => 'VS last month';

  @override
  String get monthlyBalance => 'Monthly balance';

  @override
  String get currentMonth => 'Current month';

  @override
  String get lastMonth => 'Last month';

  @override
  String get yourAccounts => 'Your accounts';

  @override
  String get yourBudgets => 'Your budgets';

  @override
  String get createBudgetToTrack => 'Create a budget to track your spending';

  @override
  String get close => 'Close';

  @override
  String get edit => 'Edit';

  @override
  String get errorDuplicatingTransaction => 'Error duplicating transaction';

  @override
  String transactionCreated(Object transaction) {
    return '\"$transaction\" has been created';
  }

  @override
  String get left => 'Left';

  @override
  String get notEnoughDataForGraph =>
      'We are sorry but there is not\nenough data to make the graph...';

  @override
  String get generalSettingsDesc => 'Edit general settings';

  @override
  String get accountsDesc => 'Add or edit your accounts';

  @override
  String get categoriesDesc => 'Add/edit categories and subcategories';

  @override
  String get budget => 'Budget';

  @override
  String get budgetDesc => 'Add or edit your budgets';

  @override
  String get importExportDesc => 'Import or export data';

  @override
  String get notificationsDesc => 'Manage your notifications settings';

  @override
  String get leaveFeedback => 'Leave a feedback';

  @override
  String get leaveFeedbackDesc =>
      'Complete a small form to report a bug or leave a feedback';

  @override
  String get appInfoDesc => 'Learn more about us and the app';
}
