// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Italian (`it`).
class AppLocalizationsIt extends AppLocalizations {
  AppLocalizationsIt([String locale = 'it']) : super(locale);

  @override
  String get appName => 'Sossoldi';

  @override
  String get dashboard => 'Dashboard';

  @override
  String get transactions => 'Transazioni';

  @override
  String get planning => 'Pianificazione';

  @override
  String get graphs => 'Grafici';

  @override
  String get list => 'Lista';

  @override
  String get categories => 'Categorie';

  @override
  String get expenses => 'Spese';

  @override
  String get incomes => 'Entrate';

  @override
  String get expense => 'Spesa';

  @override
  String get income => 'Entrata';

  @override
  String get transfer => 'Spostamento';

  @override
  String get accounts => 'Conti';

  @override
  String get details => 'Dettagli';

  @override
  String get account => 'Conto';

  @override
  String get category => 'Categoria';

  @override
  String get date => 'Data';

  @override
  String get investments => 'Investimenti';

  @override
  String get settings => 'Impostazioni';

  @override
  String get notifications => 'Notifiche';

  @override
  String get settingsDisclaimer => 'Open source, sviluppata dalla community';

  @override
  String get addTransaction => 'Aggiungi transazione';

  @override
  String get totalBalance => 'Saldo Totale';

  @override
  String get netWorth => 'Patrimonio Netto';

  @override
  String get save => 'Salva';

  @override
  String get cancel => 'Annulla';

  @override
  String get success => 'Successo';

  @override
  String get ok => 'Ok';

  @override
  String get editingTransaction => 'Modifica transazione';

  @override
  String get newTransaction => 'Nuova transazione';

  @override
  String get updateTransaction => 'Modifica transazione';

  @override
  String get recurringPayments => 'Pagamenti ricorrenti';

  @override
  String get interval => 'Intervallo';

  @override
  String get endRepetition => 'Fine ripetizione';

  @override
  String get never => 'Mai';

  @override
  String get onADate => 'In data';

  @override
  String get switchDisabled => 'Gesto disabilitato';

  @override
  String saveCsvFileFailed(Object e) {
    return 'Non puoi salvare i file qui, crea o seleziona una cartella in Downloads o Documenti. Errore: \$$e';
  }

  @override
  String errorPickingFile(Object error) {
    return 'Errore durante la selezione del file. Assicurati di avere i permessi necessari. Errore: $error';
  }

  @override
  String get storagePermissionRequired =>
      'È richiesto il permesso di archiviazione per accedere ai file.';

  @override
  String get importingData => 'Importazione dati in corso...';

  @override
  String get exportingData => 'Esportazione dati in corso...';

  @override
  String fileSavedTo(Object path) {
    return 'File salvato in: $path';
  }

  @override
  String get dataImportedSuccessfully => 'Dati importati con successo';

  @override
  String get description => 'Descrizione';

  @override
  String get addDescription => 'Aggiungi descrizione';

  @override
  String get recurringTransactionWarning =>
      'This is a transaction generated by a recurring one: any change will affect this unique transaction.\nTo change all future transactions, or recurrence options, TAP HERE.';

  @override
  String get duplicateTransactionTitle => 'Transazione duplicata';

  @override
  String get duplicateTransactionContent =>
      'Questa transazione è già presente nella lista. Vuoi duplicarla? Potrai poi modificare il nuovo inserimento.';

  @override
  String get duplicate => 'Duplica';

  @override
  String get moreFrequent => 'Più frequente';

  @override
  String get allCategories => 'Tutte le categorie';

  @override
  String get allAccounts => 'Tutte i conti';

  @override
  String errorOccurred(Object err) {
    return 'Errore: $err';
  }

  @override
  String get selectAccount => 'Seleziona conto';

  @override
  String get to => 'A:';

  @override
  String get from => 'Da:';

  @override
  String get recurringTransactionAdded => 'Transazione ricorrente aggiunta';

  @override
  String get recurringTransactions => 'Transazioni ricorrenti';

  @override
  String get addTransactionReminder => 'Aggiungi promemoria transazione';

  @override
  String get privacyPolicyTitle => 'Privacy Policy';

  @override
  String get privacyCollectTitle => 'Quali informazioni raccogliamo?';

  @override
  String get privacyChangesTitle => 'Modifiche alla Privacy Policy';

  @override
  String get contactUsTitle => 'Contattaci';

  @override
  String get privacyIntro =>
      'Sossoldi è sviluppata come un\'app open source. Questo servizio è fornito gratuitamente ed è inteso per essere utilizzato così com\'è.\nNon siamo interessati a raccogliere alcuna informazione personale. Riteniamo che tali informazioni siano solo tue. Non memorizziamo né trasmettiamo i tuoi dettagli personali, né includiamo software di pubblicità o analisi che comunichino con terze parti.\n';

  @override
  String get privacyCollectBody =>
      'Sossoldi non raccoglie alcuna informazione personale e non si connette a Internet. Qualsiasi informazione aggiunta nell\'app esiste esclusivamente sul tuo dispositivo e da nessun\'altra parte.\n';

  @override
  String get privacyChangesBody =>
      'Potremmo aggiornare la nostra Privacy Policy di tanto in tanto. Pertanto, ti consigliamo di rivedere periodicamente questa pagina per eventuali modifiche.\nQuesta policy è efficace dal 01-01-2024.\n';

  @override
  String get contactUsBody =>
      'Se hai domande o suggerimenti sulla nostra Privacy Policy, non esitare a contattarci all\'indirizzo\n';

  @override
  String get collaboratorsTitle => 'Collaboratori';

  @override
  String get meetTheTeam => 'Incontra il team';

  @override
  String get teamDescription =>
      'Sossoldi è sviluppata e mantenuta da una appassionata community open source. Ogni funzione, correzione e idea arriva da persone come te.';

  @override
  String get wantToContribute => 'Vuoi contribuire?';

  @override
  String get contributeDescription =>
      'Apri una issue, invia una PR o semplicemente saluta su GitHub';

  @override
  String get appInfo => 'Informazioni app';

  @override
  String get appVersion => 'Versione app:';

  @override
  String get collaborators => 'Collaboratori';

  @override
  String get collaboratorsDescription => 'Scopri il team dietro questa app';

  @override
  String get privacyPolicy => 'Privacy Policy';

  @override
  String get privacyPolicyDescription => 'Leggi di più';

  @override
  String get generalSettings => 'Impostazioni generali';

  @override
  String get appearance => 'Aspetto';

  @override
  String get currency => 'Valuta';

  @override
  String get requireAuthentication => 'Richiedi autenticazione';

  @override
  String get searchForATransaction => 'Cerca una transazione';

  @override
  String get selectACurrency => 'Seleziona una valuta';

  @override
  String get search => 'Cerca';

  @override
  String get searchIn => 'Cerca in';

  @override
  String get lastTransactions => 'Le tue ultime transazioni';

  @override
  String get startReconciliation => 'Avvia riconciliazione';

  @override
  String get newBalance => 'Nuovo saldo';

  @override
  String get balanceDiscrepancy => 'Differenza di saldo?';

  @override
  String get balanceAdjustmentHint =>
      'Il saldo registrato potrebbe differire dall\'estratto conto della tua banca. Tocca qui sotto per regolare manualmente il saldo e mantenere i tuoi registri aggiornati.';

  @override
  String get newAccount => 'Nuovo conto';

  @override
  String get editAccount => 'Modifica conto';

  @override
  String get createAccount => 'Crea conto';

  @override
  String get accountName => 'Nome del conto';

  @override
  String get name => 'Nome';

  @override
  String get iconAndColor => 'Icona e colore';

  @override
  String get chooseColor => 'Scegli colore';

  @override
  String get chooseIcon => 'Scegli icona';

  @override
  String get done => 'Fatto';

  @override
  String get add => 'Aggiungi';

  @override
  String get setAsMainAccount => 'Imposta come conto principale';

  @override
  String get countsForNetWorth => 'Includi nel patrimonio netto';

  @override
  String get deleteAccount => 'Elimina conto';

  @override
  String get initialBalance => 'Saldo iniziale';

  @override
  String get currentBalance => 'Saldo attuale';

  @override
  String get showLess => 'Mostra meno';

  @override
  String get showMore => 'Mostra altro';

  @override
  String get addSubcategory => 'Aggiungi sottocategoria';

  @override
  String get newCategory => 'Nuova categoria';

  @override
  String get editCategory => 'Modifica categoria';

  @override
  String get createCategory => 'Crea categoria';

  @override
  String get updateCategory => 'Aggiorna categoria';

  @override
  String get categoryName => 'Nome della categoria';

  @override
  String get type => 'Tipo';

  @override
  String get deleteCategory => 'Elimina categoria';

  @override
  String get newSubcategory => 'Nuova sottocategoria';

  @override
  String get editSubcategory => 'Modifica sottocategoria';

  @override
  String get createSubcategory => 'Crea sottocategoria';

  @override
  String get updateSubcategory => 'Aggiorna sottocategoria';

  @override
  String get subcategoryName => 'Nome della sottocategoria';

  @override
  String get deleteSubcategory => 'Elimina sottocategoria';

  @override
  String get subcategory => 'Sottocagegoria';

  @override
  String get categoryFirstThenBudget =>
      'Aggiungi una categoria prima di creare un budget';

  @override
  String inTheNextDays(Object next) {
    return 'In  $next giorni';
  }

  @override
  String get monthlyBudget => 'Budget mensile';

  @override
  String get manage => 'Gestisci';

  @override
  String get swipeLeftToDelete => 'Scorri a sinistra per eliminare';

  @override
  String get yourMonthlyBudgetWillBe => 'Il tuo budget mensile sarà:';

  @override
  String get saveBudget => 'Salva budget';

  @override
  String get selectCategoriesToCreateBudget =>
      'Seleziona le categorie per creare il tuo budget';

  @override
  String get amount => 'Importo';

  @override
  String get addCategoryBudget => 'Aggiungi budget categoria';

  @override
  String get allCategoriesAdded =>
      'Hai già aggiunto tutte le categorie disponibili.';

  @override
  String get delete => 'Elimina';

  @override
  String get allRecurringPaymentsHere =>
      'Tutti i pagamenti ricorrenti verranno visualizzati qui';

  @override
  String get addRecurringPayment => 'Aggiungi pagamento ricorrente';

  @override
  String get seeOlderPayments => 'Vedi pagamenti passati';

  @override
  String untilDate(Object date) {
    return 'Fino al $date';
  }

  @override
  String get olderPayments => 'Pagamenti passati';

  @override
  String get categoryNotFound => 'Categoria non trovata';

  @override
  String get back => 'Indietro';

  @override
  String onTheDay(Object day) {
    return '- Il giorno $day';
  }

  @override
  String get noMonthlyPaymentHistory => 'Nessuna cronologia pagamenti mensili';

  @override
  String get noRecurrentPaymentHistory =>
      'Nessuna cronologia pagamenti ricorrenti';

  @override
  String errorLoadingPayments(Object error) {
    return 'Errore nel caricamento pagamenti: $error';
  }

  @override
  String get editRecurringTransaction => 'Modifica transazione ricorrente';

  @override
  String get detailsExplanation =>
      'Dettagli (ogni modifica influenzerà solo le transazioni future)';

  @override
  String get dateStart => 'Data inizio';

  @override
  String get planned => 'Pianificato';

  @override
  String get composition => 'Composizione';

  @override
  String get progress => 'Avanzamento';

  @override
  String get noBudgetSet => 'Non ci sono budget impostati';

  @override
  String get budgetHelpText =>
      'Un budget mensile può aiutarti a tenere traccia delle tue spese e a rimanere entro i limiti';

  @override
  String get createBudget => 'Crea budget';

  @override
  String get setUpTheApp => 'Configura l\'app';

  @override
  String get setupDescription =>
      'In pochi passaggi sarai pronto a iniziare a tenere\ntraccia delle tue finanze personali (quasi) come\nMr. Rip.';

  @override
  String get startTheSetup => 'Inizia la configurazione';

  @override
  String budgetAmount(Object amount) {
    return 'Budget $amount€';
  }

  @override
  String get addBudget => 'Aggiungi budget';

  @override
  String addBudgetForCategory(Object cat) {
    return 'Aggiungi un budget per la categoria $cat';
  }

  @override
  String get addCategory => 'Aggiungi categoria';

  @override
  String get confirm => 'Conferma';

  @override
  String get step1Of2 => 'Passaggio 1 di 2';

  @override
  String get setupMonthlyBudgets => 'Imposta i tuoi budget\nmensili';

  @override
  String get chooseCategoriesForBudget =>
      'Scegli le categorie per le quali vuoi impostare un budget';

  @override
  String get monthlyBudgetTotal => 'Totale budget mensile:';

  @override
  String get nextStep => 'Passaggio successivo';

  @override
  String get continueWithoutBudget => 'Continua senza budget';

  @override
  String get step2Of2 => 'Passaggio 2 DI 2';

  @override
  String get setLiquidityInMainAccount =>
      'Imposta la liquidità nel tuo conto principale';

  @override
  String get addMoreAccounts =>
      'Sarai in grado di aggiungere altri account dall\'app';

  @override
  String get liquidityDescription =>
      'Verrà utilizzata come base a cui aggiungere entrate, spese e calcolare il tuo patrimonio.\nPotrai aggiungere altri conti all\'interno dell\'app.';

  @override
  String get mainAccount => 'Conto principale';

  @override
  String get setAmount => 'Imposta importo';

  @override
  String get editIconAndColor => 'Modifica icona e colore';

  @override
  String get skipStepOrStartFromZero =>
      'Oppure puoi saltare questo passaggio e iniziare da 0';

  @override
  String get startTrackingExpenses => 'Inizia a tracciare le tue spese';

  @override
  String get startFromZero => 'Inizia da 0';

  @override
  String get importExport => 'Importa/Esporta';

  @override
  String get importData => 'Importa dati';

  @override
  String get importDataDescription =>
      'Importa un file CSV per aggiornare il database';

  @override
  String get importMoneyManager => 'Importa da Money Manager';

  @override
  String get importMoneyManagerDescription =>
      'Importa CSV da Money Manager per aggiornare il database. Il file deve essere salvato in formato CSV da XLS.';

  @override
  String get exportData => 'Esporta dati';

  @override
  String get exportDataDescription => 'Salva i tuoi dati come file CSV';

  @override
  String get warningOverwrite => 'Attenzione: Sovrascrittura dati';

  @override
  String get warningOverwriteContent =>
      'L\'importazione di questo file sostituirà definitivamente i tuoi dati esistenti. Questa azione non può essere annullata. Assicurati di avere un backup prima di procedere.';

  @override
  String get proceedImport => 'Procedi con l\'importazione';

  @override
  String get importSuccess => 'Dati importati con successo';

  @override
  String exportFailed(Object err) {
    return 'Esportazione fallita: $err';
  }

  @override
  String errorExporting(Object tableName) {
    return 'Impossibile esportare la tabella: $tableName';
  }

  @override
  String get errorCsvNotFound => 'File CSV non trovato.';

  @override
  String get errorCsvEmpty => 'Il file CSV è vuoto.';

  @override
  String errorCsvExpectedColumn(Object column) {
    return 'Colonna mancante nel CSV: $column';
  }

  @override
  String errorCsvUnexpectedValue(Object value) {
    return 'Valore non previsto trovato: $value';
  }

  @override
  String errorCsvImportGeneral(Object error) {
    return 'Si è verificato un errore generale durante l\'importazione del CSV. Errore: $error';
  }

  @override
  String errorCsvTransactionImport(Object date) {
    return 'Errore durante l\'importazione della transazione in data: $date';
  }

  @override
  String errorCleanDatabase(Object error) {
    return 'Impossibile pulire il database. Motivo: $error';
  }

  @override
  String errorResetDatabase(Object error) {
    return 'Impossibile ripristinare il database. Motivo: $error';
  }

  @override
  String transactionCount(Object count) {
    return '$count transazioni';
  }

  @override
  String get uncategorized => 'Senza categoria';

  @override
  String get noIncomesForSelectedMonth =>
      'Nessuna entrata per il mese selezionato';

  @override
  String get noExpensesForSelectedMonth =>
      'Nessuna spesa per il mese selezionato';

  @override
  String get total => 'Totale';

  @override
  String get noTransactionsAdded => 'Non ci sono ancora transazioni aggiunte';

  @override
  String get addTransactionCallToAction =>
      'Aggiungi una transazione per rendere questa sezione più interessante';

  @override
  String get graphsEmptyState =>
      'Dopo aver aggiunto alcune transazioni, dei grafici eccezionali appariranno qui... quasi per magia!';

  @override
  String get availableLiquidity => 'Liquidità disponibile';

  @override
  String get vsLastMonth => 'VS mese scorso';

  @override
  String get monthlyBalance => 'Bilancio mensile';

  @override
  String get currentMonth => 'Mese corrente';

  @override
  String get lastMonth => 'Mese scorso';

  @override
  String get yourAccounts => 'I tuoi conti';

  @override
  String get yourBudgets => 'I tuoi budget';

  @override
  String get createBudgetToTrack =>
      'Crea un budget per monitorare le tue spese';

  @override
  String get close => 'Chiudi';

  @override
  String get edit => 'Modifica';

  @override
  String get errorDuplicatingTransaction =>
      'Errore durante la duplicazione della transazione';

  @override
  String transactionCreated(Object transaction) {
    return '\"$transaction\" è stata creata';
  }

  @override
  String get left => 'Rimanenti';

  @override
  String get notEnoughDataForGraph =>
      'Siamo spiacenti, ma non ci sono\nabbastanza dati per creare il grafico...';

  @override
  String get generalSettingsDesc => 'Modifica impostazioni generali';

  @override
  String get accountsDesc => 'Aggiungi o modifica i tuoi conti';

  @override
  String get categoriesDesc => 'Aggiungi/modifica categorie e sottocategorie';

  @override
  String get budget => 'Budget';

  @override
  String get budgetDesc => 'Aggiungi o modifica i tuoi budget';

  @override
  String get importExportDesc => 'Importa o esporta dati';

  @override
  String get notificationsDesc => 'Gestisci le impostazioni delle notifiche';

  @override
  String get leaveFeedback => 'Lascia un feedback';

  @override
  String get leaveFeedbackDesc =>
      'Compila un modulo per segnalare un bug o lasciare un feedback';

  @override
  String get appInfoDesc => 'Scopri di più su di noi e sull\'app';
}
