title: Sossoldi
description: Making an open source wealth management app for everyone.
theme: just-the-docs

url: https://theperu.github.io/sossoldi/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template