title: Sossoldi
description: Making an open source wealth management app for everyone.
theme: just-the-docs

url: https://github.com/RIP-Comm/sossoldi

aux_links:
  View it on GitHub: https://github.com/RIP-Comm/sossoldi