name: Dart Format Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Run dart format check
        run: |
          echo "Checking code formatting (default line length 80)..."
          if ! dart format --set-exit-if-changed --output=none .; then
            echo "⛔ ERROR: Code format check failed. Please run 'dart format .' on your code and commit the formatted changes."
            exit 1
          else
            echo "✅ Code format check passed."
          fi