name: test-my-app
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action/config@v3
      id: fvm-config-action

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: 'stable'
    - run: flutter test --concurrency=1
